.TH xdict 1
.SH NAME
xdict \- a command line program for accessing the MacOSX dictionary
.SH SYNOPSIS
 xdict [\-l] | [\-d [dictionary] [\-c [command]] [word]
.SH DESCRIPTION
xdict is a MacOSX command line program for accessing the MacOSX
dictionary.
.SH OPTIONS
.TP
.B \-l
If \-l is specified, all available dictionaries are listed.
.TP
.B \-d [dictionary]
If \-d is specified, xdict will try to use the specified dictionary,
if it is available.
.TP
.B \-c [command]
If \-c is specified, xdict will execute one of the following commands:
.sp
.ti
"h" or "headword" \- prints the headword only
.ti
"m" or "html"     \- prints the html version of the defintion
.ti
"r" or "raw"      \- prints the raw version of the definition
.sp
.ti
All commands except 'r' or 'raw' are ignored by the \-c option
unless \-d is also specified.
.SH PLATFORMS
xdict has been tested on MacOSX 11.x (Big Sur) and 12.x (Monterey)
on M1.
.SH HISTORY
xdict was written by Sriranga Veeraraghavan <ranga@calalum.org>.
